############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Striking"
url = "striking/"
weight = 2

[[main]]
name = "Brazillian Jiu-Jitsu"
url = "bjj/"
weight = 3

[[main]]
name = "Fitness MMA"
url = "fitness/"
weight = 4

[[main]]
weight = 5
name = "About"
hasChildren = true

[[main]]
parent = "About"
name = "Fighters"
url = "fighters/"

[[main]]
parent = "About"
name = "Coaches"
url = "coaches/"

[[main]]
parent = "About"
name = "Our Facility"
url = "facility/"

[[main]]
parent = "About"
name = "Schedule"
url = "schedule/"

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1
